[MENTORING-T-110] Kotlin PS - 2주차
BI-kotlin-in-action-2ND/HyeonminShin pull request #1
Opened 2024-01-22 12:11 UTC by TwoPair

3문제 풀었습니다.

- 1766
- 14658
- 19941

2024-01-23 13:11 UTC, konempty requested changes
크 배운것도 많지 않은데 이미 코틀린 초보자 이상의 코드 퀄리티네요 👍 👍 
조금만 수정하면 좋을것 같습니다~!

2024-01-23 13:11 UTC, konempty commented on src/14658.kt
> +data class Point(val x: Int, val y: Int)
오호 코틀린에서는 Pair라고 해서 값을 두개 넣을수 있는 기본 클래스를 지원하는데 그걸 사용해도 괜찮을것 같네요! ㅋㅋㅋㅋ

2024-01-23 13:11 UTC, konempty commented on src/14658.kt
> +}
<img width="241" alt="스크린샷 2024-01-23 오후 9 43 34" src="https://github.com/BI-kotlin-in-action-2ND/HyeonminShin/assets/44064530/0c3daa41-2502-4601-9141-f79253fb2abd">

오호 파일끝 개행이 빠져있네요 ㅋㅋㅋ..
파일끝 개행이 표준 규칙 이기도 하고 **일부**시스템에서는 에러의 원인이 되기도 한답니다 ㅋㅋㅋ
https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
요 블로그 참고해서 IDE에 파일끝 개행 설정 넣어주세요~!

2024-01-23 13:11 UTC, konempty commented on src/14658.kt
> +            cnt++
엇 뭔가 코드 포멧팅이 이상한데 첫시간에 말씀드린 코드 포멧팅 플러그인인 ktlint플러그인이 설치되어있는지 확인 부탁드립니다~!

2024-01-23 13:11 UTC, konempty commented on src/1766.kt
> +    private val graph: MutableList<MutableList<Int>> = MutableList(n + 1) { mutableListOf() }
graph는 굳이 Mutable리스트를 써서 가변성을 노출할 이유가 없을것 같습니다~!
따라서 아래와 같이 한다면 불변성을 지향하는 코드가 될것 같아요!

```kotlin
    private val graph: Array<MutableList<Int>> = Array(n + 1) { mutableListOf() }
```

2024-01-23 13:11 UTC, konempty commented on src/1766.kt
> +    private val inDegree = MutableList(n + 1) { 0 }
그리고 여기서는 기본 자료형인 IntArray를 쓰시면 가변성을 제한할수 있고 코틀린의 고유 문법을 활용할수 있어서
좀더 코틀린스러운 코드가 될것 같아요~!

참고로 IntArray도 내부 엘리먼트의 값 변경은 자유로워요 
대신, 엘리먼트의 개수는 변경이 불가능합니다~!

2024-01-23 13:11 UTC, konempty commented on src/1766.kt
> +    private val result = mutableListOf<Int>()
참고로 요긴 엘리먼트 개수의 변화가 필요한게 맞으니까 mutableListOf가 맞습니다~!

2024-01-23 13:11 UTC, konempty commented on src/1766.kt
> +    fun printResult() = println(result.joinToString(" "))
👍 👍

2024-01-23 13:11 UTC, konempty commented on src/algorithm/BinarySearch.kt
> +typealias Index = Int
ㅋㅋㅋㅋ 굳굳 좋습니다

2024-01-23 13:11 UTC, konempty commented on src/algorithm/TopologySort.kt
> +    private val inDegree = MutableList(n + 1) { 0 }
graph와 inDegree도 가변성 제한이 가능하겠네요!

2024-01-23 13:11 UTC, konempty commented on src/algorithm/TopologySort.kt
> +import java.util.*
오노 ㅠㅠㅠ
와일드 카드 임포트는 지양해야합니다 ㅠㅠㅠ
IDE 설정에서 와일드 임포트가 되지 않도록 설정 부탁드립니다

https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij

2024-01-23 13:11 UTC, konempty commented on src/14658.kt
> +    stars.forEach { star ->
```kotlin
    val cnt = stars.count { star ->
        x <= star.x && star.x <= x + l && y <= star.y && star.y <= y + l
    } 
```

코틀린은 요런 컬렉션 메소드를 지원하기때문에
조건에 맞는 엘리먼트 찾기는 요렇게 쓰는게 더 코틀린 스러운 코드입니다~!

2024-01-23 13:11 UTC, konempty commented on src/14658.kt
> +    }
요 코드를 좀더 코틀린스러운 코드로 바꾸면
```kotlin
    val result = stars.maxOf { i -> stars.maxOf { j -> capturedStar(i.x, j.y, l) } }
```
요렇게도 가능합니다~!
요건 그냥 가능성만 보여준거라 적용 안하셔도 좋습니다!

2024-01-24 07:04 UTC, TwoPair commented on src/14658.kt
> +data class Point(val x: Int, val y: Int)
그걸 고려하긴 했는데 사용할 때 직관적인 네이밍의 클래스를 사용하고자 한 것도 있고, 멤버 변수에 접근할 때 first, second를 통해 각 축에 access하는게 가독성이 좋지 않아 그랬습니다.
프로파일링을 해보진 않았지만 성능 상으로도 크게 차이가 있을 것 같진 않아 그대로 둘 것 같은데 어떻게 생각하시나요?

2024-01-24 08:44 UTC, TwoPair commented
`ktlint` 체크해주는 gitAction을 추가했는데 따로 PR 없이 main 브랜치에 커밋 했습니다.

2024-01-24 11:23 UTC, konempty commented on src/14658.kt
> +data class Point(val x: Int, val y: Int)
역시 ㅋㅋㅋ 그런 이유일거라고 생각했어요
요것도 단순 추천사항이라 그런 이유라면 지금 하신게 올바른 코드입니다~!

2024-01-24 11:26 UTC, konempty approved these changes
크 굳굳 너무 좋습니다~!
리뷰드릴 내용이 없네요 ㅋㅋㅋ
바로 머지하셔도 좋을듯합니다!

2024-01-24 16:02 UTC, merged